### ISSUE TITLE
Keep getting 404

### ISSUE THREAD

**Issue by hshar7** [dradis/dradis-api#1]
I have CE dradis, each time I try to submit a request it gives me 404.

My settings point to http://localhost:3000/ which is how I access my dradis instance and password points to the shared one.

**Comment by rachkor** [comment]
@hshar7 could you post a sample request? For example: 

`$ curl -u 'example@email.com' http://localhost:3000/api/issues`

Also, feel free to post about this in the community forum here: http://discuss.dradisframework.org/

**Comment by etdsoft** [comment]
heads up @hshar7 @rachkor this is an old repo (2-years!), the current API code lives under dradis/dradis-ce here:

https://github.com/dradis/dradis-ce/tree/master/engines/dradis-api

HTH
